name: Publish Q-Sys Plugin

on:
  push:
    tags:
    - '*'

jobs:
  pack-and-push-job:
    runs-on: ubuntu-latest
    name: A job to package and publish Q-Sys Community Plugins
    steps:
      - name: Copy Files into Workflow directory
        uses: actions/checkout@v1

      - name: Pack and Push Plugin
        uses: soloworks/publish-q-sys-plugin@v1
        with:
          nuget-host: "https://q-sys.soloworks.co.uk/q-sys-community-plugins/"
          api-key: ${{ secrets.NUGET_APIKEY }}
          md-to-desc: "description.md"
